$$ ITI \space AI-Pro: \space Intake \space 44 $$
$$ Machine \space Learning \space 1 $$
$$ Lab \space no. \space 4 $$

# `01` Import Necessary Libraries

## `i` Default Libraries

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

## `ii` Additional Libraries
Add imports for additional libraries you used throughout the notebook

In [1]:
from sklearn.svm import LinearSVC
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
from sklearn.model_selection import train_test_split

----------------------------

# `02` Load Data

Note: Make sure the `Data` folder attached with the notebook is in the same path for this cell to work properly.

[Dataset Link](https://www.kaggle.com/datasets/parisrohan/credit-score-classification)

In [3]:
# I saved my prapared data from my last assignment

In [4]:
X_train = pd.read_csv(r'E:\ITI AI&ML\13.Machine Learning 1\labs\Lab 4\X_train.csv')
y_train = pd.read_csv(r'E:\ITI AI&ML\13.Machine Learning 1\labs\Lab 4\y_train.csv')
X_test = pd.read_csv(r'E:\ITI AI&ML\13.Machine Learning 1\labs\Lab 4\X_test.csv')
y_test = pd.read_csv(r'E:\ITI AI&ML\13.Machine Learning 1\labs\Lab 4\y_test.csv')

In [5]:
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((127548, 23), (127548, 1), (20000, 23), (20000, 1))

In [7]:
X_train.head()

Month   Age  Occupation  Annual_Income  Monthly_Inhand_Salary  \
0    6.0  45.0           5       63501.72               5471.810   
1    2.0  28.4          14        8504.55                934.712   
2    3.0  27.0           3      101066.40               8547.200   
3    5.0  18.0          12       37353.58               2926.798   
4    3.0  31.0           3       26053.36               2059.113   

   Num_Bank_Accounts  Num_Credit_Card  Interest_Rate  Num_of_Loan  \
0                9.0              8.0           21.0          2.0   
1                8.0              6.0           23.0          7.0   
2                4.0              4.0           12.0          2.0   
3                6.0              9.0           34.0          8.0   
4                8.0              6.0           11.0          2.0   

   Delay_from_due_date  ...  Credit_Mix  Outstanding_Debt  \
0                 18.0  ...           1       2056.370117   
1                 23.0  ...           1       2870.020020   
2                 28.0  ...           2       1461.270020   
3                 15.0  ...           0       3459.090088   
4                 12.0  ...           2       1339.709961   

   Credit_Utilization_Ratio  Payment_of_Min_Amount  Total_EMI_per_month  \
0                    38.423                      2              105.239   
1                    38.084                      1               26.611   
2                    41.362                      2               95.707   
3                    31.541                      2              172.345   
4                    29.100                      2               39.730   

   Amount_invested_monthly  Payment_Behaviour  Monthly_Balance  \
0                   83.198                5.0          608.744   
1                   42.381                1.0          314.479   
2                  280.611                4.0          684.104   
3                  124.141                4.0          276.194   
4                  184.751                1.0          271.430   

   Credit_Age_years  Credit_Age_months  
0              24.0                6.0  
1              25.0                7.0  
2              31.0                5.0  
3              16.0                0.0  
4              11.8                4.4  

[5 rows x 23 columns]

In [8]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 127548 entries, 0 to 127547
Data columns (total 23 columns):
 #   Column                    Non-Null Count   Dtype  
---  ------                    --------------   -----  
 0   Month                     127548 non-null  float64
 1   Age                       127548 non-null  float64
 2   Occupation                127548 non-null  int64  
 3   Annual_Income             127548 non-null  float64
 4   Monthly_Inhand_Salary     127548 non-null  float64
 5   Num_Bank_Accounts         127548 non-null  float64
 6   Num_Credit_Card           127548 non-null  float64
 7   Interest_Rate             127548 non-null  float64
 8   Num_of_Loan               127548 non-null  float64
 9   Delay_from_due_date       127548 non-null  float64
 10  Num_of_Delayed_Payment    127548 non-null  float64
 11  Changed_Credit_Limit      127548 non-null  float64
 12  Num_Credit_Inquiries      127548 non-null  float64
 13  Credit_Mix                127548 non-null  i

In [9]:
# So the train and test set are ready to the model  

----------------------

# `05` Linear Support Vector Machine Classifier

Using `sklearn` implementation of linear support vector machine classifiers to model the data.

Hint: Look for `sklearn.svm.LinearSVC` class.

## `i` Baseline Model Training

Initializing the model with initial parameters, fitting it to the training data, and get a baseline model.

Use:
- `random_state` $= 1234$

In [11]:
# Initialize the model with initial parameters
svm_model = LinearSVC(random_state=1234)

In [12]:
# Fit the model to the training data
svm_model.fit(X_train, y_train.values.ravel())

c:\Users\bios\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\svm\_classes.py:31: FutureWarning: The default value of `dual` will change from `True` to `'auto'` in 1.5. Set the value of `dual` explicitly to suppress the warning.
  warnings.warn(
c:\Users\bios\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\svm\_base.py:1237: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


LinearSVC(random_state=1234)

In [13]:
# Make predictions on the test set
y_pred = svm_model.predict(X_test)

In [14]:
y_pred

array([2, 1, 3, ..., 2, 2, 2], dtype=int64)

## `ii` Model Evaluation

Evaluate the baseline model performance using classification metrics, e.g. **Accuracy**, **Precision**, $F_1 \space Score$, **Confusion Matrix** etc.

Which metric is more reliable?

In [15]:
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.50265


In [20]:
precision = precision_score(y_test, y_pred, average=None)
print("Precision:", precision)

Precision: [0.63430261 0.59232614 0.35639834]


In [21]:
precision = precision_score(y_test, y_pred, average='weighted')
print("Precision:", precision)

Precision: 0.5626748178231588


In [23]:
recall = recall_score(y_test, y_pred, average = None)
print("Recall:", recall)

Recall: [0.22201139 0.55620191 0.80056417]


In [24]:
recall = recall_score(y_test, y_pred, average = 'weighted')
print("Recall:", recall)

Recall: 0.50265


In [26]:
f1 = f1_score(y_test, y_pred, average = None)
print("F1 Score:", f1)

F1 Score: [0.32890365 0.57369593 0.49322211]


In [27]:
f1 = f1_score(y_test, y_pred, average = 'weighted')
print("F1 Score:", f1)

F1 Score: 0.48847890139716127


In [28]:
conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(conf_matrix)

Confusion Matrix:
[[1287 3401 1109]
 [ 714 5928 4016]
 [  28  679 2838]]


----------------------

# `06` Kernelized Support Vector Machine Classifier

Using `sklearn` implementation of kernelized support vector machine classifiers to model the data.

Hint: Look for `sklearn.svm.SVC` class.

## `i` Baseline Model Training

Initializing the model with initial parameters, fitting it to the training data, and get a baseline model.

Use:
- `random_state` $= 1234$
- `kernel` = 'linear'

In [31]:
# Initialize the model with initial parameters
svm_model = SVC(random_state=1234, kernel='linear')

In [6]:
# the model takes so much time so I will divide the data to get output 
X_train_split, X_val_split, y_train_split, y_val_split = train_test_split(X_train, y_train, test_size=0.2, random_state=1234, stratify=y_train)

In [32]:
# Fit the model to the training data
svm_model.fit(X_train, y_train.values.ravel())

In [ ]:
y_pred = svm_model.predict(X_test)

## `ii` Model Evaluation

Evaluate the baseline model performance using classification metrics, e.g. **Accuracy**, **Precision**, $F_1 \space Score$, **Confusion Matrix** etc.

`Q` Which metric is more reliable?
`Q` Compare the results to those of `sklearn.svm.LinearSVC` class. Also, is there a difference in the training time?

In [ ]:
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

## `iii` Kernelization Mode: On

Let's try the both `poly` and `rbf` kernels. Use default $C, \gamma, \space and/or \space degree$ parameter(s) for simplicity if you want. Does kernelization make the model better?

Which of the two kernels performs better?

## `iv` Tuning Hyperparameters

Try different  $C, \gamma, \space and/or \space degree$ values and evaluate. What is the best hyperparamters value combination?

Remember that $alpha=\frac{1}{C}$ which means less regularization for higher $C$ values.

`Hint:` Make sure to tune only relevant hyperparameters per kernel (e.g., don't tune different values for `degree` while using `rbf` kernel)

`Note:` You can tune other parameters as you see fit (but make sure you elaborate your reasoning.

Hint: You might want to use `sklearn.model_selection.RandomizedSearchCV` or `sklearn.model_selection.GridSearchCV` classes.

------------------

# `07` Generalization Error

Now that we have tuned our solution, to an *extent*, we need to test for a final time on the held out test set.

-----------------------------

# `Bonus` Better Flow

For the model to be production-ready, we need to integrate it into a pipeline along with the data preparation flow.

Hint: Look up `sklearn.pipeline.Pipeline` class.

----------------------------------------------

$$ Wish \space you \space all \space the \space best \space ♡ $$
$$ Abdelrahman \space Eid $$